spring.application.name=sano

spring.data.mongodb.uri=mongodb://sano:sano@localhost:27017/sano-db

# o valores separados:
# spring.data.mongodb.host=localhost
# spring.data.mongodb.port=27017
# spring.data.mongodb.database=sano-db